# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe773fc48910b4e1bed2f8fe1af244b3e5cfd2515773ba96f077ce83aebe18b4d19ba251b16a1601054aebd409c1febd6a5347a7b741f053bc4ceb2d92560ac5

test:
  secret_key_base: f83842e2527c4a00e21c79e352a174c816249264024d2eecbaa1e8c1b8f50c58f62b018c96c148f9994bd4bfa9d6667bbaaa58c7ad39a3aa6bcf0deded63e3f4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
